import fs from "fs";
import path from "path";

const name = process.argv[2];
if (!name) {
  console.error("❌ Usage: node generate-page.js <PageName>");
  process.exit(1);
}

const dir = path.resolve(`apps/web/src/pages/${name}`);
fs.mkdirSync(dir, { recursive: true });

fs.writeFileSync(
  path.join(dir, "index.astro"),
  `<h1>${name} Page</h1>\n<p>Generated by tools/codegen</p>\n`
);

console.log(`✅ Page created: ${dir}/index.astro`);
